name: Build Windows Executable

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/setup-vcpp@v1
      with:
        windows-sdk: latest

    - name: Compile
      run: |
        cl /EHsc owsjho.cpp user32.lib gdi32.lib

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: SquatJumpOverlay
        path: owsjho.exe
