name: Build owsjho.cpp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSVC environment
      uses: ilammy/msvc-setup@v1

    - name: Compile with MSVC
      run: cl /W4 owsjho.cpp /link user32.lib
