name: Build owsjho.cpp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSVC environment and compile
      shell: cmd
      run: |
        for /f "usebackq tokens=*" %%i in (`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do set "VSINSTALLDIR=%%i"
        echo Visual Studio installation directory: %VSINSTALLDIR%
        call "%VSINSTALLDIR%\VC\Auxiliary\Build\vcvarsall.bat" x64 && cl /W4 owsjho.cpp /link user32.lib
    
