name: Build owsjho.cpp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSVC environment and compile
      shell: cmd
      run: |
        REM Locate Visual Studio installation with vswhere.
        for /f "usebackq tokens=*" %%i in (`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do (
            set "VSINSTALLDIR=%%i"
        )
        echo Visual Studio installation directory: %VSINSTALLDIR%
        REM Initialize the MSVC environment.
        call "%VSINSTALLDIR%\VC\Auxiliary\Build\vcvars64.bat"
        REM Compile the code.
        cl /W4 owsjho.cpp /link user32.lib
