name: Build Windows Executable

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: '17.0'
        architecture: x64

    - name: Compile
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cl /EHsc /Fe:owsjho.exe owsjho.cpp user32.lib gdi32.lib /link /SUBSYSTEM:WINDOWS

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SquatJumpOverlay
        path: owsjho.exe
