name: Build Windows Executable

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Native Tools
      uses: llvm/actions/setup@v1
      with:
        compiler: cl

    - name: Compile Windows Application
      run: |
        cl /nologo /EHsc /Fe:owsjho.exe owsjho.cpp ^
        /link /SUBSYSTEM:WINDOWS /ENTRY:mainCRTStartup user32.lib gdi32.lib

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SquatJumpOverlay
        path: owsjho.exe
